name: MineReporter
main: com.github.Shiul93.MineReporter
version: 0.1

commands:
  report:
    description: Report something
    usage: /report [user] [reason] [description...]
  reports:
    description: Manage reports

